---
- name: Install Chromium
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - libnss3
    - chromium-browser
 
- name: Set Chromium policies to allow autoplay
  become: yes
  block:
    - name: Create policy directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc
        - /etc/chromium-browser
        - /etc/chromium-browser/policies
        - /etc/chromium-browser/policies/managed
        - /etc/chromium-browser/policies/recommended
    - name: Set autoplay policy
      copy:
        content: { "AutoplayAllowed": "true" }
        dest: /etc/chromium-browser/policies/managed/autoplay_policy.json
        mode: 0400

- name: Set Chromium command
  set_fact:
    appcommand: "chromium-browser {{ frontend_url }} --window-size=${SCREEN_WIDTH},${SCREEN_HEIGHT} --start-fullscreen --kiosk --incognito --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disk-cache-dir=/dev/null --autoplay-policy=no-user-gesture-required --no-user-gesture-required --disable-features=PreloadMediaEngagementData,AutoplayIgnoreWebAudio,MediaEngagementBypassAutoplayPolicies,TranslateUI"

- name: Install Arduino make
  become: yes
  apt:
    name: arduino-mk
    state: present
    # TODO: user toevoegen aan groep dialout?

- name: Download and install Docker
  become: yes
  block:
    - name: Add an Apt signing key for Docker, will not download if present (Ubuntu)
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository for Ubuntu
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ubuntu is defined and ubuntu
    - name: Add an Apt signing key for Docker, will not download if present (Raspbian)
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 
        url: https://download.docker.com/linux/raspbian/gpg
        state: present
    - name: Add Docker repository for Raspbian
      apt_repository:
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
        state: present
      when: raspberry_pi is defined and raspberry_pi
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install Docker
      apt:
        state: present
        name: "{{ item }}"
      loop:
        - python-docker
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose

- name: Download beademingstoestel from git
  become: yes
  #become_user: breathneyfrontend
  block:
    - name: Create beademingstoestel directories
      file:
        group: breathney
        owner: breathney
        #mode: 0700
        mode: 0777
        #path: /home/pi/beademingstoestel
        path: "{{ item }}"
        state: directory
      loop:
        #- /usr/share/ventilator
        - /home/breathney/beademingstoestel/frontend_installer
    - name: Checkout repository frontend_installer
      git:
        repo: 'https://github.com/beademingstoestel/frontend_installer.git'
        dest: /home/breathney/beademingstoestel/frontend_installer
        #version: release-0.22
 
- name: Set udev rules for Arduino
  become: yes
  block:
  - name: Copy rules to /etc/udev/rules.d
    copy: remote_src=True src=/home/breathney/beademingstoestel/frontend_installer/99-arduino.rules dest=/etc/udev/rules.d/99-arduino.rules
    notify: reboot_frontend
  - name: Set permissions on arduino rules file
    file:
      path: /etc/udev/rules.d/99-arduino.rules
      owner: root
      group: root
      mode: '0644'

- name: Create symbolic link to ventilator
  become: yes
  file:
    src: "/dev/null"
    dest: "/dev/ventilator"
    state: link

- name: Run `docker-compose up`
  become: yes
  docker_compose:
    project_src: /home/breathney/beademingstoestel/frontend_installer
    #build: no
    state: present

- name: Remove link on /dev/ventilator
  become: yes
  file:
    path: /dev/ventilator
    state: absent

