---
- name: Remove default Raspbian server
  become: yes
  apt_repository:
    repo: deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
    state: absent
  when: raspberry_pi is defined and raspberry_pi

- name: Install apt key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9165938D90FDDD2E
    state: present

- name: Install Unix Solutions raspbian mirror
  become: yes
  apt_repository:
    repo: deb http://mirror.unix-solutions.be/raspbian/raspbian/ stretch main contrib non-free rpi
    state: present
    update_cache: yes
  when: raspberry_pi is defined and raspberry_pi

#- name: Upgrade all packages
#  become: yes
#  apt:
#    autoclean: yes
#    autoremove: yes
#    cache_valid_time: 3600
#    update_cache: yes
#    upgrade: full

- name: Install some basic packages
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    cache_valid_time: 3600
    name: "{{ basic_packages }}"
    state: present
    update_cache: yes

- name: Install extra packages for nmcli
  become: yes
  apt:
    autoclean: yes
    autoremove: yes
    cache_valid_time: 3600
    name:
      - libnm-glib4
      - python-dbus
      - gir1.2-networkmanager-1.0
    state: present
    update_cache: yes
  when: networkmanager is defined and networkmanager
